#This is a script generated with an R package 'annotated'. It is supposed to be used as a library of annotations within the function 'annotated()'. Created on: 2019-02-10 21:38:32

list(
 annotation = list(
  cond1 = c(
    "",
    "",
    "Full call to the function lm.",
    "",
    "Basic info about residuals distribution. In linear models residuals are assumed to be normally distributed, if they are not, the model may provide biased estimates.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "R squared is very small, it means the predictors do not predict the dependent variable vary well.",
    "F statistic tests a very weak hypothesis if at least one predictor makes a difference for the dependent variable. It is rare when this hypothesis can be rejected.",
    ""),
  cond2 = c(
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "R squared is very large. It's a good sign.",
    "",
    ""),
  cond3 = c(
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "The R squared is average, acceptable.",
    "",
    "")
 ),
 conditions = list(
  cond1 = c(
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ob$r.squared < 0.1",
    "",
    ""),
  cond2 = c(
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ob$r.squared > 0.7",
    "",
    ""),
  cond3 = c(
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ob$r.squared > 0.1 & ob$r.squared < 0.7",
    "",
    "")
 ),
methods.for = "summary.lm"
)
